# Generated by Django 5.0.6 on 2024-06-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
